language: java
jdk:
- openjdk8
branches:
  only:
  - main
services:
  - docker

before_install:
- docker run --rm --name mypg -v ${PWD}/app/src/main/resources:/docker-entrypoint-initdb.d -p 5432:5432 -e POSTGRES_PASSWORD="password" -e POSTGRES_USER="masil" -e POSTGRES_DB="playthegames" -d postgres

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./gradlew clean build"

