/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.slipp.masil;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.scheduling.annotation.EnableAsync;

@SpringBootApplication
@EnableAsync
public class App {

    public static void main(String[] args) {
        ConfigurableApplicationContext app = SpringApplication.run(App.class, args);
    }
}
